### ISSUE TITLE
Please stop removing already-imported installed games from game list upon each disconnect, thank you

### ISSUE THREAD

**Issue by ghost** [FriendsOfGalaxy/galaxy-integration-paradox#9]
Lack of installed game makes more hassle than uninstalled game displaying as installed.

Paradox keeps disconnecting the plugin often so not removing games marked as installed may serve as a decent QoL crutch until the situation with disconnects would sort itself.

**Comment by FriendsOfGalaxy** [comment]
Hey @DrinkFromTheCup , I agree.

Unfortunately there is no clean way in Galaxy to both:
- import installed games
- import owned games and all stuff that requires connection

Each connection lose turns of the plugin and all local games features and requires reconnecting data once again. Alternatively we can be silent, and do not inform Galaxy that the plugin lost connection. Then you'll have installed games but no longer sync about owned games. But maybe that is not a big deal as only the game list is imported, no achievements, so there is point to reconnect ony after purchasing the another Paradox game.

Third option is to tell Galaxy we're "offline". But currently that implies you cannot launch games as well. That is Galaxy bug.

What do you think?

**Comment by ghost** [comment]
Apologies for necro'ing this theme. Missed the notification somehow.

>Each connection lose turns of the plugin and all local games features and requires reconnecting data once again.

Somehow, Amazon/Twitch integration kept my stuff counted and accounted despite being Disconnected from Amazon/Twitch's side. So I though it was a feature of that integration - which might be transferred to this integration to avoid this extremely irritating behaviour. I'll drop them a bug report then.

**Comment by FriendsOfGalaxy** [comment]
It may be a feature of amazon/twitch platform. As far as I know twitch integration authorizes using locally stored token.
